### ISSUE TITLE
upstreaming

### ISSUE THREAD

**Issue by hippi777** [ymir-linux/void-packages#28]
hi there! :)

u may want to join this conversation:
https://github.com/void-linux/void-packages/issues/25901

**Comment by drake-newell** [comment]
I might, but they seem pretty adamant about not having other kernels. Also, @reback00 and I have been working on adding individual patches from Parabola that make semi-free packages in the main void repos truly free by FSF standards (minus the unused nonfree repos of course). One such program is the texlive suite. Because of this, it probably makes more sense to do our own thing. However, it would be great if they could be persuaded.

**Comment by hippi777** [comment]
sorry for late, as i wrote there, i think there are more options than simply not having the libre kernel (etc), and maybe its just a matter of getting a better server, but i can see something like a tendency that things are initiated, and then at a point closed by inactivity, and then considered as already "discussed". :D (btw maybe im wrong about this.) it feels like void is mostly settled with its directives, or maybe it is simply about giving a solution instead of suggesting anything, but things have more causes than this alone.

maybe ur patches could be optional, and then only the default options will remain in question, but i think most importantly its about the maintenance of the branches, while if something is either free or nonfree according to an option, then the organization of the packages dont really fit to this.

also, if the templates are shared, then it would be enough to have a repo with some custom packages and the rest can still use the default as a fallback, like when one has a local repo just for a few bits.

however this still isnt about getting a ryf cert, as void itself wont get it as of the current guidelines, but it could still be an official support for a fully free experience, but i see ur point, and that its not an easy case anyhow...

**Comment by drake-newell** [comment]
I think the main issue that upstreaming doesn't solve is that users would have to mess with dependencies and the packages would not be available in a repo. We already rely on void repos for all packages that we don't need to change since we don't have the resources to build them all, and we only have our repo for linux-libre and other patched packages. We deploy our custom repo using a modified base-files and remove dependency issues with a modified base-system (depends on the linux-libre metapackage, not linux). All of these packages are compiled in our server and can be incorporated into ISOs for people to use. The only thing upstreaming would change is whether I merge upstream changes to our forked repo once in a while, which takes very little time. It would be nice, but would also block us from easily compiling our 200 or so patched packages other than linux-libre because of the way void-packages and xbps-src handle patches.

**Comment by reback00** [comment]
If I understand correctly, by "upstreaming" you mean that we should make the upstream (in this case void-linux/void-packages) into libre so that we don't have to maintain a separate repo like this. Is this correct?

**Comment by hippi777** [comment]
by upstreaming, i mean that the 2 `void-packages` repos could be identical, or better said, merged into one, as i know about the options for the templates, and what i was thinking about is controlling all the differences by those; while im not sure about their scope, so if anything can't be done with them (i guess its not an actual issue); and im also not sure about the required effort of merging such huge repos with probably kinda much differences...

ive never done merging, i know about auto-merging, but i dont know how much conflicts comes with each merging and how much manual work is required for resolving any. however if it takes any manual work, then thats already much according to the rushing development of void, to keep everything in sync. otherwise this seems to be the answer for this: "The only thing upstreaming would change is whether I merge upstream changes to our forked repo once in a while, which takes very little time."

it would be also good if these changes would find their way back into void, so this is also a thing i was thinking about as upstreaming.

other than these, i was thinking about fragmentation, it is probably never good, ur project goals are just as valuable as they sound, but most of the power is still around void, and thats why i was searching for a way for any kinda reunion. :D 

so, after all, u folks, and Duncaen on the other side, gave me much better understanding, and now the scope of what i initiated reduced purely to the level of the templates.

and yes, so many thanks! :)

**Comment by reback00** [comment]
Hmm. Well, I don't think full upstreaming can be done, since they have less resources for linux-libre. If some changes are upstreamed (e.g. liberated packages), we can benefit from it too. There will be more eyes on them, that means more contributions, fixes, improvements etc.

I'd still be happy if Void has a `libre` repo with liberated packages, without linux-libre kernel. That's still better than nothing.

For linux-libre however, it seems users will still have to rely on this project. Also, I wish that someday we'll be able to apply for FSDG approval. :1st_place_medal:

**Comment by hippi777** [comment]
my last message is over there, i hope i didnt forget to reply to anything that i wanted/could so, but i think it would be the best to continue the whole conversation there, cuz it is about to become a mess by the 2 parallel threads, and i hope it will be fine for everyone, but feel free to decide otherwise, im the intern around here, not everyone else, so u may know better what and how... :D

**Comment by reback00** [comment]
No problem, what I posted here is nothing important. The main discussion is still going on there.

**Comment by reback00** [comment]
Unfortunately seems like [not going to happen](https://github.com/void-linux/void-packages/issues/25901#issuecomment-720078121). So closing, at least for now. We can open again if we need to.

**Comment by hippi777** [comment]
fine, and thx for all! :)
